# Generated by Django 4.0.10 on 2024-01-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module40app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='name_index',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='name-index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='cat-brand-index'),
        ),
    ]
